stages:
  - build
  - test
  - release

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

build-frontend:
  stage: build
  rules:
    - changes:
        - frontend/**/*
      when: always
    - when: manual
  image:
    name: gcr.io/kaniko-project/executor:v1.20.1-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --dockerfile "${CI_PROJECT_DIR}/frontend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/momo-store-frontend:$VERSION"
      --build-arg VERSION=$VERSION
      --cache=true

include:
  - template: Jobs/SAST.gitlab-ci.yml

release-frontend:
  stage: release
  needs:
    - nodejs-scan-sast
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - crane tag ${CI_REGISTRY_IMAGE}/momo-store-frontend:$VERSION latest