stages:
  - test
  - build
  - release

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

include:
  - template: Jobs/SAST.gitlab-ci.yml

build-frontend-docker:
  stage: build
  needs:
    - nodejs-scan-sast
    - semgrep-sast
  image:
    name: gcr.io/kaniko-project/executor:v1.20.1-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/frontend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/momo-store-frontend:$VERSION"
      --build-arg VERSION=$VERSION
      --cache=true

release-frontend-docker:
  stage: release
  needs:
    - build-frontend-docker
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - crane tag ${CI_REGISTRY_IMAGE}/momo-store-frontend:$VERSION latest