services:
  backend:
    image: backend:latest
    ports:
      - "8081:8081"

  frontend:
    image: frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - VUE_APP_API_URL=http://backend:8081