services:
  backend:
    build:
      dockerfile: backend/Dockerfile
    ports:
      - "8081:8081"

  frontend:
    build:
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend