stages:
  - create-k8s-cluster
  - deploy-app-via-helm

terraform:
  stage: create-k8s-cluster
  trigger:
    include:
      - "/infra/terraform/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - infra/terraform/**/*

helm:
  stage: deploy-app-via-helm
  trigger:
    include:
      - "/infra/helm/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - infra/helm/**/*