stages:
  - module-infra

terraform:
  stage: module-infra
  trigger:
    include:
      - "/infra/terraform/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - infra/terraform/**/*

helm:
  stage: module-infra
  trigger:
    include:
      - "/infra/helm/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - infra/helm/**/*