{{- if .Values.ingress.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: {{ .Values.ingress.tls.clusterIssuer.server }}
    email: {{ .Values.ingress.tls.clusterIssuer.email }}
    privateKeySecretRef:
      name: letsencrypt-prod-secret
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingress.className }}
{{- end }}