kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.dockerconfigjson.name }}
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ .Values.dockerconfigjson.data }}
type: kubernetes.io/dockerconfigjson